github: [kamil-alekber] # Replace with up to 4 GitHub Sponsors-enabled usernames
# patreon: kamil-alekber  # Replace with a single Patreon username
# open_collective: kamil-alekber  # Replace with a single Open Collective username
# ko_fi: kamil-alekber     # Replace with a single Ko-fi username
# tidelift: pypi/your-package-name  # Replace with Tidelift platform-name/package-name
# community_bridge: project-name    # Replace with a single Community Bridge project-name
# liberapay: kamil-alekber # Replace with a single Liberapay username
# issuehunt: kamil-alekber # Replace with a single IssueHunt username
# otechie: kamil-alekber   # Replace with a single Otechie username
# lfx_crowdfunding: project-name    # Replace with a single LFX Crowdfunding project-name
# custom: ['https://example.com']   # Replace with up to 4 custom sponsorship URLs
